import { createMatch, send, pass, currentFrame } from '../expeditionRules.ts';
const site = (id: string) => ({ id, name: `Site ${id}`, medium: 'gas', temperatureC: { low: -50, high: 80 } });
const worlds = [0,1,2,3,4,5,6,7,8].map((i) => ({ planet: `W${i}`, element: 'metal', planetKey: `w${i}`, temperatureC: { low: -50, high: 80 }, sites: [site(`w${i}s0`)] })) as any[];
let uid = 0;
const rec = (o: any = {}) => ({ id: `f${++uid}`, species: 'graviclaw', provenance: { schemaVersion: '1.0.0', origin: 'x' }, element: { primary: 'metal', affinities: { metal: 100 } }, archetype: { key: 'predator', favors: [] }, attributes: { strength: 50, vitality: 50, endurance: 50, agility: 50, reflex: 50, intelligence: 50, willpower: 50, instinct: 50, charisma: 50, resilience: 50, ...(o.attributes||{}) }, physiology: { environmentalTolerance: { ambientMedia: ['gas'], temperatureC: { min: -60, max: 90 } }, breathes: ['gas'], capabilities: {}, senses: {} }, traits: [], temperament: { boldness: 50, curiosity: 50, energy: 50, aggression: 50, sociability: 50 }, abilities: [{ name: 'Hit', signature: true, instrument: 'fists', action: 'strike', medium: 'metal', intensity: 60 }] }) as any;
const twelve = (s: string) => Array.from({ length: 12 }, (_, i) => ({ ...rec(), id: `${s}_${i}` }));
let state: any = createMatch({ rosterA: twelve('A'), rosterB: twelve('B'), worlds, seed: 'fight-seed' });
state = { ...state, starter: 'A', turn: 'A' };
const sid = currentFrame(state).sites[0].id;
state = send(state, 'A', 'A_0', sid); state = send(state, 'B', 'B_0', sid);
state = pass(state, state.turn); state = pass(state, state.turn);
console.log(JSON.stringify(state.resolutionLog.map((e: any) => ({ t: e.type, r: e.recordId, tg: e.target, o: e.outcome, p: e.power, rem: e.remaining, x: e.exchange }))));
