module.exports = {
    STAT_POINT_MAX: 999,
    STAT_COUNT_PER_CHARACTER: 9,
    MAX_ELEMENT_COUNT_PER_CHARACTER: 3,
    STAT_THRESHOLD_VARIABILITY: 0.25,
    LOW_THRESHOLD: 0.25,
    MEDIUM_THRESHOLD: 0.5,
    HIGH_THRESHOLD: 0.75
}