terraform {
  backend "s3" {
    bucket       = "xalians-terraform-state-174497891311"
    key          = "xalians/terraform.tfstate"
    region       = "us-east-1"
    encrypt      = true
    use_lockfile = true
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.2"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }

  required_version = ">= 1.10"
}

provider "aws" {
  region = var.aws_region
}


#########################################################
#####                     IAM                       #####
#########################################################
resource "aws_iam_role" "lambda_exec" {
  name = "serverless_lambda"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Sid    = ""
      Principal = {
        Service = "lambda.amazonaws.com"
      }
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "lambda_policy" {
  role       = aws_iam_role.lambda_exec.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# Scoped in place of AmazonDynamoDBFullAccess: only the live tables the
# handlers read and write, only the actions they actually call. The showroom
# function (GET /xalians/showroom) does not touch DynamoDB at all, but it
# shares this role with the rest, so it also ends up with this scoped access
# rather than none; splitting into per-function roles is out of scope here.
#
# XalianTable is deliberately absent (issue #180): the legacy creature flow and
# every handler that read that table are gone, so nothing needs access to it.
resource "aws_iam_role_policy" "dynamodb_policy" {
  name = "xalian-dynamodb-access"
  role = aws_iam_role.lambda_exec.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "XalianTables"
        Effect = "Allow"
        Action = [
          "dynamodb:GetItem",
          "dynamodb:BatchGetItem",
          "dynamodb:PutItem",
          "dynamodb:UpdateItem",
          "dynamodb:Query",
          "dynamodb:DeleteItem",
          "dynamodb:ConditionCheckItem",
        ]
        Resource = [
          "arn:aws:dynamodb:${var.aws_region}:${data.aws_caller_identity.current.account_id}:table/XalianUsersTable",
          # Exact table names, not a table-level wildcard, so each table needs its own
          # ARN here. The index wildcard below covers XalianRegistry's byOwner GSI.
          "arn:aws:dynamodb:${var.aws_region}:${data.aws_caller_identity.current.account_id}:table/XalianRegistry",
          "arn:aws:dynamodb:${var.aws_region}:${data.aws_caller_identity.current.account_id}:table/Xalian*/index/*",
        ]
      },
    ]
  })
}
#####                                               #####
#########################################################

#########################################################
#####                COMMON LAMBDA                  #####
#########################################################
# The bucket name was originally generated by a random_pet resource; it is now
# pinned to the live bucket so state can be rebuilt via import blocks
# (random_pet resources cannot be imported).
resource "aws_s3_bucket" "lambda_bucket" {
  bucket        = var.lambda_bucket_name
  force_destroy = true
}

# lambda zip
#
# apps/api is built by esbuild (npm run build -w apps/api, wired into
# .github/workflows/deploy-backend.yml before this runs) into apps/api/dist/<handler>/
# index.mjs, one bundle per handler with @aws-sdk/* left external (the nodejs22.x runtime
# provides it) and everything else, including the @xalians/content JSON, inlined. This
# zips that bundle directory directly; there is no excludes list because dist/ contains
# nothing but the six handler bundles.
data "archive_file" "lambda_zip_file" {
  type        = "zip"
  source_dir  = "${path.module}/apps/api/dist"
  output_path = "${path.module}/generate_xalian_lambda.zip"
}

# lambda bucket object
# (aws_s3_bucket_object was removed in AWS provider v5; after migrating old state run:
#   terraform state rm aws_s3_bucket_object.lambda_bucket_object
# and let this re-upload on the next apply)
resource "aws_s3_object" "lambda_bucket_object" {
  bucket = aws_s3_bucket.lambda_bucket.id
  key    = "generate_xalian_lambda.zip"
  source = data.archive_file.lambda_zip_file.output_path
  # source_hash rather than etag: S3 stores a multipart etag for larger uploads, which
  # never matches filemd5() locally, so etag produced a diff on every single apply.
  # source_hash is compared against its own stored value, so it changes only when the
  # zip contents actually change.
  source_hash = data.archive_file.lambda_zip_file.output_base64sha256
}
#####                                               #####
#########################################################


#########################################################
#####               API Gateway Common              #####
#########################################################
resource "aws_apigatewayv2_api" "lambda" {
  name          = "XalianAPIGateway"
  protocol_type = "HTTP"
  cors_configuration {
    allow_origins     = ["http://*", "https://*"]
    allow_methods     = ["GET", "OPTIONS", "PUT", "PATCH", "POST", "DELETE", "HEAD"]
    allow_headers     = ["host", "authorization", "x-amz-date", "X-Amz-Security-Token", "Content-Type"]
    allow_credentials = true
    max_age           = 300
  }
}

resource "aws_apigatewayv2_stage" "prod" {
  # route_settings names "GET /xalians/showroom"; API Gateway rejects the stage update
  # when that route does not exist yet, so the stage must wait for the module that
  # creates it (seen on the 2026-09-10 apply that introduced the route).
  depends_on = [module.showroom_xalian_lambda_module]

  api_id = aws_apigatewayv2_api.lambda.id

  name        = "prod"
  auto_deploy = true

  # Tuned levers, not fixed limits: revisit if legitimate traffic gets
  # throttled or if the free generator route needs tighter protection.
  default_route_settings {
    throttling_burst_limit = 50
    throttling_rate_limit  = 20
  }

  # The free lever is the one anonymous route, so it keeps its own tighter
  # throttle (the vision doc's ratified "endpoint gets API Gateway throttling
  # regardless").
  route_settings {
    route_key              = "GET /xalians/showroom"
    throttling_burst_limit = 10
    throttling_rate_limit  = 5
  }

  access_log_settings {
    destination_arn = aws_cloudwatch_log_group.api_gw.arn

    format = jsonencode({
      requestId               = "$context.requestId"
      sourceIp                = "$context.identity.sourceIp"
      requestTime             = "$context.requestTime"
      protocol                = "$context.protocol"
      httpMethod              = "$context.httpMethod"
      resourcePath            = "$context.resourcePath"
      routeKey                = "$context.routeKey"
      status                  = "$context.status"
      responseLength          = "$context.responseLength"
      integrationErrorMessage = "$context.integrationErrorMessage"
      }
    )
  }
}

resource "aws_apigatewayv2_stage" "test" {
  # route_settings names "GET /xalians/showroom"; API Gateway rejects the stage update
  # when that route does not exist yet, so the stage must wait for the module that
  # creates it (seen on the 2026-09-10 apply that introduced the route).
  depends_on = [module.showroom_xalian_lambda_module]

  api_id = aws_apigatewayv2_api.lambda.id

  name        = "test"
  auto_deploy = true

  # Tuned levers, not fixed limits: revisit if legitimate traffic gets
  # throttled or if the free generator route needs tighter protection.
  default_route_settings {
    throttling_burst_limit = 50
    throttling_rate_limit  = 20
  }

  # The free lever is the one anonymous route, so it keeps its own tighter
  # throttle (the vision doc's ratified "endpoint gets API Gateway throttling
  # regardless").
  route_settings {
    route_key              = "GET /xalians/showroom"
    throttling_burst_limit = 10
    throttling_rate_limit  = 5
  }

  access_log_settings {
    destination_arn = aws_cloudwatch_log_group.api_gw.arn

    format = jsonencode({
      requestId               = "$context.requestId"
      sourceIp                = "$context.identity.sourceIp"
      requestTime             = "$context.requestTime"
      protocol                = "$context.protocol"
      httpMethod              = "$context.httpMethod"
      resourcePath            = "$context.resourcePath"
      routeKey                = "$context.routeKey"
      status                  = "$context.status"
      responseLength          = "$context.responseLength"
      integrationErrorMessage = "$context.integrationErrorMessage"
      }
    )
  }
}

resource "aws_cloudwatch_log_group" "api_gw" {
  name              = "/aws/api_gw/${aws_apigatewayv2_api.lambda.name}"
  retention_in_days = 7
}
#####                                               #####
#########################################################


#########################################################
#####            COGNITO JWT AUTHORIZER             #####
#########################################################
# Replaces AWS_IAM + frontend SigV4 signing on the /db/* routes. The audience and issuer
# ids come from apps/web/src/aws-exports.js (aws_user_pools_web_client_id, aws_user_pools_id).
resource "aws_apigatewayv2_authorizer" "cognito" {
  api_id           = aws_apigatewayv2_api.lambda.id
  authorizer_type  = "JWT"
  identity_sources = ["$request.header.Authorization"]
  name             = "cognito-user-pool"

  jwt_configuration {
    audience = [var.cognito_web_client_id]
    issuer   = "https://cognito-idp.${var.aws_region}.amazonaws.com/${var.cognito_user_pool_id}"
  }
}
#####                                               #####
#########################################################

#########################################################
#####               LAMBDA INSTANCE                 #####
##             Table Retrieve User Lambda              ##
#########################################################
module "table_retrieve_xalian_user_lambda_module" {
  source = "./terraform/modules/lambda"

  function_name                   = "TableRetrieveXalianUser"
  lambda_handler_path             = "retrieveUser/index.handler"
  apigw_lambda_route_key          = "GET /db/user"
  lambda_bucket_id                = aws_s3_bucket.lambda_bucket.id
  lambda_bucket_object_key        = aws_s3_object.lambda_bucket_object.key
  lambda_archive_file_output_hash = data.archive_file.lambda_zip_file.output_base64sha256
  iam_role_arn                    = aws_iam_role.lambda_exec.arn
  apigw_lambda_id                 = aws_apigatewayv2_api.lambda.id
  base_apigw_lambda_execution_arn = aws_apigatewayv2_api.lambda.execution_arn
  authorization_type              = "JWT"
  authorizer_id                   = aws_apigatewayv2_authorizer.cognito.id
}
#####                                               #####
#########################################################

#########################################################
#####               LAMBDA INSTANCE                 #####
##              Table Create User Lambda               ##
#########################################################
module "table_create_xalian_user_lambda_module" {
  source = "./terraform/modules/lambda"

  function_name                   = "TableCreateXalianUser"
  lambda_handler_path             = "createUser/index.handler"
  apigw_lambda_route_key          = "POST /db/user"
  lambda_bucket_id                = aws_s3_bucket.lambda_bucket.id
  lambda_bucket_object_key        = aws_s3_object.lambda_bucket_object.key
  lambda_archive_file_output_hash = data.archive_file.lambda_zip_file.output_base64sha256
  iam_role_arn                    = aws_iam_role.lambda_exec.arn
  apigw_lambda_id                 = aws_apigatewayv2_api.lambda.id
  base_apigw_lambda_execution_arn = aws_apigatewayv2_api.lambda.execution_arn
  authorization_type              = "JWT"
  authorizer_id                   = aws_apigatewayv2_authorizer.cognito.id
}
#####                                               #####
#########################################################

#########################################################
#####               LAMBDA INSTANCE                 #####
##              Table Update User Lambda               ##
#########################################################
module "table_update_xalian_user_lambda_module" {
  source = "./terraform/modules/lambda"

  function_name                   = "TableUpdateXalianUser"
  lambda_handler_path             = "updateUser/index.handler"
  apigw_lambda_route_key          = "PATCH /db/user"
  lambda_bucket_id                = aws_s3_bucket.lambda_bucket.id
  lambda_bucket_object_key        = aws_s3_object.lambda_bucket_object.key
  lambda_archive_file_output_hash = data.archive_file.lambda_zip_file.output_base64sha256
  iam_role_arn                    = aws_iam_role.lambda_exec.arn
  apigw_lambda_id                 = aws_apigatewayv2_api.lambda.id
  base_apigw_lambda_execution_arn = aws_apigatewayv2_api.lambda.execution_arn
  authorization_type              = "JWT"
  authorizer_id                   = aws_apigatewayv2_authorizer.cognito.id
}
#####                                               #####
#########################################################

#########################################################
#####               LAMBDA INSTANCE                 #####
##          Generate Registry Xalian Lambda (D1)       ##
#########################################################
module "generate_registry_xalian_lambda_module" {
  source = "./terraform/modules/lambda"

  function_name                   = "GenerateRegistryXalian"
  lambda_bucket_id                = aws_s3_bucket.lambda_bucket.id
  lambda_bucket_object_key        = aws_s3_object.lambda_bucket_object.key
  lambda_handler_path             = "generateRegistryXalian/index.handler"
  lambda_archive_file_output_hash = data.archive_file.lambda_zip_file.output_base64sha256
  iam_role_arn                    = aws_iam_role.lambda_exec.arn
  apigw_lambda_id                 = aws_apigatewayv2_api.lambda.id
  apigw_lambda_route_key          = "POST /xalians"
  base_apigw_lambda_execution_arn = aws_apigatewayv2_api.lambda.execution_arn
  authorization_type              = "JWT"
  authorizer_id                   = aws_apigatewayv2_authorizer.cognito.id
}
#####                                               #####
#########################################################

#########################################################
#####               LAMBDA INSTANCE                 #####
##           List Registry Xalians Lambda (D1)         ##
#########################################################
module "list_registry_xalians_lambda_module" {
  source = "./terraform/modules/lambda"

  function_name                   = "ListRegistryXalians"
  lambda_bucket_id                = aws_s3_bucket.lambda_bucket.id
  lambda_bucket_object_key        = aws_s3_object.lambda_bucket_object.key
  lambda_handler_path             = "listRegistryXalians/index.handler"
  lambda_archive_file_output_hash = data.archive_file.lambda_zip_file.output_base64sha256
  iam_role_arn                    = aws_iam_role.lambda_exec.arn
  apigw_lambda_id                 = aws_apigatewayv2_api.lambda.id
  apigw_lambda_route_key          = "GET /xalians"
  base_apigw_lambda_execution_arn = aws_apigatewayv2_api.lambda.execution_arn
  authorization_type              = "JWT"
  authorizer_id                   = aws_apigatewayv2_authorizer.cognito.id
}
#####                                               #####
#########################################################

#########################################################
#####               LAMBDA INSTANCE                 #####
##          Retrieve Registry Xalian Lambda (D1)       ##
#########################################################
module "retrieve_registry_xalian_lambda_module" {
  source = "./terraform/modules/lambda"

  function_name                   = "RetrieveRegistryXalian"
  lambda_bucket_id                = aws_s3_bucket.lambda_bucket.id
  lambda_bucket_object_key        = aws_s3_object.lambda_bucket_object.key
  lambda_handler_path             = "retrieveRegistryXalian/index.handler"
  lambda_archive_file_output_hash = data.archive_file.lambda_zip_file.output_base64sha256
  iam_role_arn                    = aws_iam_role.lambda_exec.arn
  apigw_lambda_id                 = aws_apigatewayv2_api.lambda.id
  apigw_lambda_route_key          = "GET /xalians/{xalianId}"
  base_apigw_lambda_execution_arn = aws_apigatewayv2_api.lambda.execution_arn
  authorization_type              = "JWT"
  authorizer_id                   = aws_apigatewayv2_authorizer.cognito.id
}
#####                                               #####
#########################################################

#########################################################
#####               LAMBDA INSTANCE                 #####
##       Public Retrieve Registry Xalian Lambda        ##
#########################################################
module "retrieve_public_registry_xalian_lambda_module" {
  source = "./terraform/modules/lambda"

  function_name                   = "RetrievePublicRegistryXalian"
  lambda_bucket_id                = aws_s3_bucket.lambda_bucket.id
  lambda_bucket_object_key        = aws_s3_object.lambda_bucket_object.key
  lambda_handler_path             = "retrievePublicRegistryXalian/index.handler"
  lambda_archive_file_output_hash = data.archive_file.lambda_zip_file.output_base64sha256
  iam_role_arn                    = aws_iam_role.lambda_exec.arn
  apigw_lambda_id                 = aws_apigatewayv2_api.lambda.id
  apigw_lambda_route_key          = "GET /registry/xalians/{xalianId}"
  base_apigw_lambda_execution_arn = aws_apigatewayv2_api.lambda.execution_arn
  authorization_type              = "NONE"
}
#####                                               #####
#########################################################

#########################################################
#####               LAMBDA INSTANCE                 #####
##        Public List Registry Xalians Lambda          ##
#########################################################
module "list_public_registry_xalians_lambda_module" {
  source = "./terraform/modules/lambda"

  function_name                   = "ListPublicRegistryXalians"
  lambda_bucket_id                = aws_s3_bucket.lambda_bucket.id
  lambda_bucket_object_key        = aws_s3_object.lambda_bucket_object.key
  lambda_handler_path             = "listPublicRegistryXalians/index.handler"
  lambda_archive_file_output_hash = data.archive_file.lambda_zip_file.output_base64sha256
  iam_role_arn                    = aws_iam_role.lambda_exec.arn
  apigw_lambda_id                 = aws_apigatewayv2_api.lambda.id
  apigw_lambda_route_key          = "GET /registry/owners/{ownerId}/xalians"
  base_apigw_lambda_execution_arn = aws_apigatewayv2_api.lambda.execution_arn
  authorization_type              = "NONE"
}
#####                                               #####
#########################################################

#########################################################
#####               LAMBDA INSTANCE                 #####
##           Release Registry Xalian Lambda            ##
#########################################################
module "release_registry_xalian_lambda_module" {
  source = "./terraform/modules/lambda"

  function_name                   = "ReleaseRegistryXalian"
  lambda_bucket_id                = aws_s3_bucket.lambda_bucket.id
  lambda_bucket_object_key        = aws_s3_object.lambda_bucket_object.key
  lambda_handler_path             = "releaseRegistryXalian/index.handler"
  lambda_archive_file_output_hash = data.archive_file.lambda_zip_file.output_base64sha256
  iam_role_arn                    = aws_iam_role.lambda_exec.arn
  apigw_lambda_id                 = aws_apigatewayv2_api.lambda.id
  apigw_lambda_route_key          = "DELETE /xalians/{xalianId}"
  base_apigw_lambda_execution_arn = aws_apigatewayv2_api.lambda.execution_arn
  authorization_type              = "JWT"
  authorizer_id                   = aws_apigatewayv2_authorizer.cognito.id
}
#####                                               #####
#########################################################

#########################################################
#####               LAMBDA INSTANCE                 #####
##               Showroom Xalian Lambda                ##
#########################################################
# The free lever: the one route on this API with no authorizer. It generates a
# ratified record and persists nothing, so an anonymous visitor can pull it as
# often as they like; both stages give the route its own tighter throttle above.
module "showroom_xalian_lambda_module" {
  source = "./terraform/modules/lambda"

  function_name                   = "ShowroomXalian"
  lambda_bucket_id                = aws_s3_bucket.lambda_bucket.id
  lambda_bucket_object_key        = aws_s3_object.lambda_bucket_object.key
  lambda_handler_path             = "showroomXalian/index.handler"
  lambda_archive_file_output_hash = data.archive_file.lambda_zip_file.output_base64sha256
  iam_role_arn                    = aws_iam_role.lambda_exec.arn
  apigw_lambda_id                 = aws_apigatewayv2_api.lambda.id
  apigw_lambda_route_key          = "GET /xalians/showroom"
  base_apigw_lambda_execution_arn = aws_apigatewayv2_api.lambda.execution_arn
  authorization_type              = "NONE"
}
#####                                               #####
#########################################################



// reference the cert that is created already
# Find a certificate issued by (not imported into) ACM
// data "aws_acm_certificate" "amazon_issued" {
//   domain      = "*.xalians.com"
//   types       = ["AMAZON_ISSUED"]
//   most_recent = true
// }

resource "aws_apigatewayv2_domain_name" "api" {
  domain_name = "api.xalians.com"

  domain_name_configuration {
    certificate_arn = var.cert_arn
    endpoint_type   = "REGIONAL"
    security_policy = "TLS_1_2"
  }
}

resource "aws_apigatewayv2_domain_name" "testapi" {
  domain_name = "testapi.xalians.com"

  domain_name_configuration {
    certificate_arn = var.cert_arn
    endpoint_type   = "REGIONAL"
    security_policy = "TLS_1_2"
  }
}



// ROUTE 53

data "aws_route53_zone" "xalian_zone" {
  name = "xalians.com"
}

resource "aws_route53_record" "api" {
  zone_id = data.aws_route53_zone.xalian_zone.zone_id
  name    = aws_apigatewayv2_domain_name.api.domain_name
  type    = "A"

  alias {
    name                   = aws_apigatewayv2_domain_name.api.domain_name_configuration[0].target_domain_name
    zone_id                = aws_apigatewayv2_domain_name.api.domain_name_configuration[0].hosted_zone_id
    evaluate_target_health = true
  }
}

resource "aws_apigatewayv2_api_mapping" "api_mapping" {
  api_id      = aws_apigatewayv2_api.lambda.id
  domain_name = aws_apigatewayv2_domain_name.api.id
  stage       = aws_apigatewayv2_stage.prod.id
}

resource "aws_apigatewayv2_api_mapping" "testapi_mapping" {
  api_id      = aws_apigatewayv2_api.lambda.id
  domain_name = aws_apigatewayv2_domain_name.testapi.id
  stage       = aws_apigatewayv2_stage.test.id
}




###################
# react front end #
###################

# AWS provider v5 split the old inline acl/policy/website/cors arguments into
# dedicated resources. The import blocks below adopt the existing live
# configuration on first plan after the provider upgrade; they are no-ops once
# the resources are in state.
resource "aws_s3_bucket" "react_bucket" {
  bucket = var.frontend_bucket_name
}

resource "aws_s3_bucket_policy" "react_bucket" {
  bucket = aws_s3_bucket.react_bucket.id

  policy = <<EOF
{
  "Id": "bucket_policy_site",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "PublicRead",
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::${var.frontend_bucket_name}",
        "arn:aws:s3:::${var.frontend_bucket_name}/*"
      ],
      "Principal": "*"
    }
  ]
}
EOF
}

resource "aws_s3_bucket_website_configuration" "react_bucket" {
  bucket = aws_s3_bucket.react_bucket.id

  index_document {
    suffix = "index.html"
  }

  error_document {
    key = "index.html"
  }
}

# The site distribution (#203). Created in the console long before Terraform
# and imported here so the deep-link error mapping lives in code: the S3
# origin answers every client-side route (/generator, /encyclopedia/...) with
# a 404 whose body is index.html, and CloudFront must rewrite that status to
# 200 or every deep link is logged as an error and read by crawlers as a
# missing page. 403 is mapped the same way for the day the bucket policy
# stops answering missing keys with 404. Everything else matches the live
# distribution exactly so the import plans as an update, never a replace.
import {
  to = aws_cloudfront_distribution.site
  id = var.cloudfront_id
}

resource "aws_cloudfront_distribution" "site" {
  enabled             = true
  is_ipv6_enabled     = true
  http_version        = "http2"
  price_class         = "PriceClass_100"
  default_root_object = "index.html"
  aliases             = ["www.xalians.com", "xalians.com"]

  origin {
    origin_id   = var.frontend_bucket_name
    domain_name = "${var.frontend_bucket_name}.s3.us-east-1.amazonaws.com"
    # No s3_origin_config: the live origin has an empty access identity (the
    # bucket is public-read) and the provider treats the omitted block as that.
  }

  default_cache_behavior {
    target_origin_id           = var.frontend_bucket_name
    viewer_protocol_policy     = "redirect-to-https"
    allowed_methods            = ["GET", "HEAD", "OPTIONS"]
    cached_methods             = ["GET", "HEAD"]
    compress                   = true
    cache_policy_id            = "658327ea-f89d-4fab-a63d-7e88639e58f6" # Managed-CachingOptimized
    origin_request_policy_id   = "88a5eaf4-2fd4-4709-b370-b4c650ea3fcf" # Managed-CORS-S3Origin
    response_headers_policy_id = "5cc3b908-e619-4b99-88e5-2cf7f45965bd" # Managed-CORS-With-Preflight
  }

  custom_error_response {
    error_code            = 404
    response_code         = 200
    response_page_path    = "/index.html"
    error_caching_min_ttl = 10
  }

  custom_error_response {
    error_code            = 403
    response_code         = 200
    response_page_path    = "/index.html"
    error_caching_min_ttl = 10
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    acm_certificate_arn      = var.cert_arn
    ssl_support_method       = "sni-only"
    minimum_protocol_version = "TLSv1.2_2021"
  }

  lifecycle {
    prevent_destroy = true
  }
}

# The site's own DNS. The www record was created in the console alongside the
# distribution and is imported here; the apex record is new -- xalians.com was
# listed as a distribution alias and covered by the certificate, but had no
# record, so only www resolved. Both are alias records to the distribution;
# Z2FDTNDATAQYW2 is CloudFront's fixed hosted zone id.
import {
  to = aws_route53_record.site_www
  id = "${var.hosted_zone_id}_www.${var.frontend_bucket_name}_A"
}

resource "aws_route53_record" "site_www" {
  zone_id = data.aws_route53_zone.xalian_zone.zone_id
  name    = "www.${var.frontend_bucket_name}"
  type    = "A"

  alias {
    name                   = aws_cloudfront_distribution.site.domain_name
    zone_id                = aws_cloudfront_distribution.site.hosted_zone_id
    evaluate_target_health = true
  }
}

resource "aws_route53_record" "site_apex" {
  zone_id = data.aws_route53_zone.xalian_zone.zone_id
  name    = var.frontend_bucket_name
  type    = "A"

  alias {
    name                   = aws_cloudfront_distribution.site.domain_name
    zone_id                = aws_cloudfront_distribution.site.hosted_zone_id
    evaluate_target_health = true
  }
}

resource "aws_s3_bucket_cors_configuration" "react_bucket" {
  bucket = aws_s3_bucket.react_bucket.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET"]
    allowed_origins = ["*"]
    max_age_seconds = 3000
  }
}

// api gateway domain name

// resource "aws_apigatewayv2_domain_name" "ui" {
//   domain_name = "xalians.com"

//   domain_name_configuration {
//     certificate_arn = var.cert_arn
//     endpoint_type   = "REGIONAL"
//     security_policy = "TLS_1_2"
//   }
// }

// route53 for frontend


// STILL NEED THIS IT IS JUST ALREADY CREATED
// data "aws_cloudfront_distribution" "distribution" {
//   id = var.cloudfront_id
// }

// resource "aws_route53_record" "www-xalians-frontend" {
//   zone_id = data.aws_route53_zone.xalian_zone.zone_id
//   name    = "www.xalians.com"
//   type    = "A"

//   alias {
//     name = data.aws_cloudfront_distribution.distribution.domain_name
//     // name = aws_s3_bucket.react_bucket.website_domain
//     // zone_id = aws_s3_bucket.react_bucket.hosted_zone_id
//     zone_id = data.aws_cloudfront_distribution.distribution.hosted_zone_id
//     evaluate_target_health = true
//   }
// }



















// terraform {
//   required_providers {
//     aws = {
//       source  = "hashicorp/aws"
//       version = "~> 3.48.0"
//     }
//     random = {
//       source  = "hashicorp/random"
//       version = "~> 3.1.0"
//     }
//     archive = {
//       source  = "hashicorp/archive"
//       version = "~> 2.2.0"
//     }
//   }

//   required_version = "~> 1.0"
// }

// provider "aws" {
//   region = var.aws_region
// }

// resource "random_pet" "lambda_bucket_name" {
//   prefix = "chronic-labs"
//   length = 4
// }

// resource "aws_s3_bucket" "lambda_bucket" {
//   bucket = random_pet.lambda_bucket_name.id
//   acl           = "private"
//   force_destroy = true
// }

// # copy to s3 bucket

// data "archive_file" "lambda_zip" {
//   type = "zip"

//   // source_dir  = "../${path.root}/src"
//   // output_path = "../${path.root}/lambda_zip.zip"
//   source_dir  = "${path.root}/src"
//   output_path = "${path.root}/lambda_zip.zip"
// }

// resource "aws_s3_bucket_object" "lambda_zip_s3_object" {
//   bucket = aws_s3_bucket.lambda_bucket.id

//   key    = "lambda_zip.zip"
//   source = data.archive_file.lambda_zip.output_path

//   etag = filemd5(data.archive_file.lambda_zip.output_path)
// }

// resource "aws_iam_role" "lambda_exec" {
//   name = "serverless_lambda"

//   assume_role_policy = jsonencode({
//     Version = "2012-10-17"
//     Statement = [{
//       Action = "sts:AssumeRole"
//       Effect = "Allow"
//       Sid    = ""
//       Principal = {
//         Service = "lambda.amazonaws.com"
//       }
//       }
//     ]
//   })
// }

// resource "aws_iam_role_policy_attachment" "lambda_policy" {
//   role       = aws_iam_role.lambda_exec.name
//   policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
// }



// # API gateway

// resource "aws_apigatewayv2_api" "lambda" {
//   name          = "xalian_api_gateway"
//   protocol_type = "HTTP"
// }

// resource "aws_apigatewayv2_stage" "prod" {
//   api_id = aws_apigatewayv2_api.lambda.id

//   name        = "prod"
//   auto_deploy = true

//   access_log_settings {
//     destination_arn = aws_cloudwatch_log_group.api_gw.arn

//     format = jsonencode({
//       requestId               = "$context.requestId"
//       sourceIp                = "$context.identity.sourceIp"
//       requestTime             = "$context.requestTime"
//       protocol                = "$context.protocol"
//       httpMethod              = "$context.httpMethod"
//       resourcePath            = "$context.resourcePath"
//       routeKey                = "$context.routeKey"
//       status                  = "$context.status"
//       responseLength          = "$context.responseLength"
//       integrationErrorMessage = "$context.integrationErrorMessage"
//       }
//     )
//   }
// }

// resource "aws_apigatewayv2_stage" "test" {
//   api_id = aws_apigatewayv2_api.lambda.id

//   name        = "test"
//   auto_deploy = true

//   access_log_settings {
//     destination_arn = aws_cloudwatch_log_group.api_gw.arn

//     format = jsonencode({
//       requestId               = "$context.requestId"
//       sourceIp                = "$context.identity.sourceIp"
//       requestTime             = "$context.requestTime"
//       protocol                = "$context.protocol"
//       httpMethod              = "$context.httpMethod"
//       resourcePath            = "$context.resourcePath"
//       routeKey                = "$context.routeKey"
//       status                  = "$context.status"
//       responseLength          = "$context.responseLength"
//       integrationErrorMessage = "$context.integrationErrorMessage"
//       }
//     )
//   }
// }

// resource "aws_cloudwatch_log_group" "api_gw" {
//   name = "/aws/api_gw/${aws_apigatewayv2_api.lambda.name}"

//   retention_in_days = 30
// }



// // reference the cert that is created already
// # Find a certificate issued by (not imported into) ACM
// // data "aws_acm_certificate" "amazon_issued" {
// //   domain      = "*.xalians.com"
// //   types       = ["AMAZON_ISSUED"]
// //   most_recent = true
// // }

// resource "aws_apigatewayv2_domain_name" "api" {
//   domain_name = "api.xalians.com"

//   domain_name_configuration {
//     certificate_arn = var.cert_arn
//     endpoint_type   = "REGIONAL"
//     security_policy = "TLS_1_2"
//   }
// }

// resource "aws_apigatewayv2_domain_name" "testapi" {
//   domain_name = "testapi.xalians.com"

//   domain_name_configuration {
//     certificate_arn = var.cert_arn
//     endpoint_type   = "REGIONAL"
//     security_policy = "TLS_1_2"
//   }
// }



// // ROUTE 53

// data "aws_route53_zone" "xalian_zone" {
//     name = "xalians.com"
// }

// resource "aws_route53_record" "api" {
//   zone_id = data.aws_route53_zone.xalian_zone.zone_id
//   name    = aws_apigatewayv2_domain_name.api.domain_name
//   type    = "A"

//   alias {
//     name                   = aws_apigatewayv2_domain_name.api.domain_name_configuration[0].target_domain_name
//     zone_id                = aws_apigatewayv2_domain_name.api.domain_name_configuration[0].hosted_zone_id
//     evaluate_target_health = true
//   }
// }

// resource "aws_apigatewayv2_api_mapping" "api_mapping" {
//   api_id      = aws_apigatewayv2_api.lambda.id
//   domain_name = aws_apigatewayv2_domain_name.api.id
//   stage       = aws_apigatewayv2_stage.prod.id
// }

// resource "aws_apigatewayv2_api_mapping" "testapi_mapping" {
//   api_id      = aws_apigatewayv2_api.lambda.id
//   domain_name = aws_apigatewayv2_domain_name.testapi.id
//   stage       = aws_apigatewayv2_stage.test.id
// }




// ###################
// # react front end #
// ###################

// resource "aws_s3_bucket" "react_bucket" {
//   bucket = "${var.frontend_bucket_name}"
//   acl    = "public-read"

//   policy = <<EOF
// {
//   "Id": "bucket_policy_site",
//   "Version": "2012-10-17",
//   "Statement": [
//     {
//       "Sid": "PublicRead",
//       "Action": [
//         "s3:GetObject"
//       ],
//       "Effect": "Allow",
//       "Resource": [
//         "arn:aws:s3:::${var.frontend_bucket_name}",
//         "arn:aws:s3:::${var.frontend_bucket_name}/*"
//       ],
//       "Principal": "*"
//     }
//   ]
// }
// EOF

//   website {
//     index_document = "index.html"
//     error_document = "index.html"
//   }

//   cors_rule {
//     allowed_headers = ["*"]
//     allowed_methods = ["GET"]
//     allowed_origins = ["*"]
//     max_age_seconds = 3000
//   }
// }

// // api gateway domain name

// // resource "aws_apigatewayv2_domain_name" "ui" {
// //   domain_name = "xalians.com"

// //   domain_name_configuration {
// //     certificate_arn = var.cert_arn
// //     endpoint_type   = "REGIONAL"
// //     security_policy = "TLS_1_2"
// //   }
// // }

// // route53 for frontend

// data "aws_cloudfront_distribution" "distribution" {
//   id = var.cloudfront_id
// }

// resource "aws_route53_record" "www-xalians-frontend" {
//   zone_id = data.aws_route53_zone.xalian_zone.zone_id
//   name    = "www.xalians.com"
//   type    = "A"

//   alias {
//     name = data.aws_cloudfront_distribution.distribution.domain_name
//     // name = aws_s3_bucket.react_bucket.website_domain
//     // zone_id = aws_s3_bucket.react_bucket.hosted_zone_id
//     zone_id = data.aws_cloudfront_distribution.distribution.hosted_zone_id
//     evaluate_target_health = true
//   }
// }




#########################################################
#####                  DATABASE                     #####
#########################################################
# Both tables were created by hand outside Terraform. Key schema and settings
# below were verified against the live tables with describe-table on
# 2026-09-10: PAY_PER_REQUEST billing, no GSIs, no streams, no TTL, no SSE
# configured (defaults), and point-in-time recovery currently DISABLED on
# both. This resource turns PITR on, which is a real, intended change on
# import, not a drift correction.
#
# The `import` blocks below adopt the live tables into state on the next
# apply. prevent_destroy guards against a future change to these resources
# (for example the key-design rework tracked in issue #20) accidentally
# planning a destroy/recreate of tables that hold real user data.

# RETAINED, READ BY NOTHING (issue #180). The legacy creature flow and every handler
# that touched this table are deleted, and no Lambda role grants access to it any more.
# The resource stays, with prevent_destroy and point-in-time recovery, because it still
# holds the ~70 records people kept under the old system; what becomes of them (migrate
# to XalianRegistry, export, or drop) is Nick's decision, not this change's.
resource "aws_dynamodb_table" "xalian_table" {
  name         = "XalianTable"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "speciesId"
  range_key    = "xalianId"

  attribute {
    name = "speciesId"
    type = "S"
  }

  attribute {
    name = "xalianId"
    type = "S"
  }

  point_in_time_recovery {
    enabled = true
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_dynamodb_table" "xalian_users_table" {
  name         = "XalianUsersTable"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "userId"

  attribute {
    name = "userId"
    type = "S"
  }

  point_in_time_recovery {
    enabled = true
  }

  lifecycle {
    prevent_destroy = true
  }
}

import {
  to = aws_dynamodb_table.xalian_table
  id = "XalianTable"
}

import {
  to = aws_dynamodb_table.xalian_users_table
  id = "XalianUsersTable"
}

# XalianRegistry (D1): the table for server-generated, ratified records (@xalians/rules
# XalianRecord). New, not imported -- Terraform creates it on apply. hash key xalianId
# (the record's own id) with a byOwner GSI (ownerId + generatedAt, newest first) for
# listing a caller's own generated Xalians. prevent_destroy for the same reason as the two
# legacy tables: this holds real user data the moment the first record is generated.
resource "aws_dynamodb_table" "xalian_registry" {
  name         = "XalianRegistry"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "xalianId"

  attribute {
    name = "xalianId"
    type = "S"
  }

  attribute {
    name = "ownerId"
    type = "S"
  }

  attribute {
    name = "generatedAt"
    type = "S"
  }

  global_secondary_index {
    name            = "byOwner"
    hash_key        = "ownerId"
    range_key       = "generatedAt"
    projection_type = "ALL"
  }

  point_in_time_recovery {
    enabled = true
  }

  lifecycle {
    prevent_destroy = true
  }
}
#####                                               #####
#########################################################
