/*
	Type-level regression for issue #181: registries.json's closed vocabularies used to
	widen to `string` through the zod enums in packages/content/src/schema/registries.ts,
	because `resolveJsonModule` types every JSON string as plain `string`. types.ts covered
	the gap by hand-writing eight closed unions (AttributeKey, CapabilityKey,
	GradedSenseKey, TemperamentKey, ElementKey, Chirality, Corporeality, Finish) as a
	second source for the same keys -- a "one source per data kind" violation.

	The fix (packages/content/src/registriesConst.ts, generated by scripts/bundleLore.js,
	feeding the zod enums in registries.ts) makes the schema's own z.infer types the
	literal unions, and types.ts now only re-exports them. This file is a compile-time
	check that the re-exported types are still the narrow literal unions they were before
	-- not `string` -- so a regression (e.g. someone widening a schema back to
	`z.array(z.string())`) fails `npm run typecheck -w packages/rules`, not just at
	runtime. There is nothing to assert at runtime; the `// @ts-expect-error` lines below
	are the actual check, and `tsc --noEmit` fails loudly if an expected error stops
	occurring (an unused ts-expect-error directive is itself a compile error).
*/
import { describe, expect, test } from 'vitest';
import type {
	AttributeKey,
	CapabilityKey,
	Chirality,
	Corporeality,
	ElementKey,
	Finish,
	GradedSenseKey,
	TemperamentKey,
} from '../types.ts';

// A valid literal member of each union type-checks with no cast.
const attribute: AttributeKey = 'strength';
const capability: CapabilityKey = 'flight';
const gradedSense: GradedSenseKey = 'sight';
const temperament: TemperamentKey = 'boldness';
const element: ElementKey = 'fire';
const chirality: Chirality = 'levo';
const corporeality: Corporeality = 'corporeal';
const finish: Finish = 'standard';

// An arbitrary string does NOT type-check against any of them -- this is exactly the
// widening bug from #181: before the fix, every one of these lines compiled cleanly
// because the type behind each alias was `string`.
// @ts-expect-error 'not-a-key' is not an AttributeKey
const badAttribute: AttributeKey = 'not-a-key';
// @ts-expect-error 'not-a-key' is not a CapabilityKey
const badCapability: CapabilityKey = 'not-a-key';
// @ts-expect-error 'not-a-key' is not a GradedSenseKey
const badGradedSense: GradedSenseKey = 'not-a-key';
// @ts-expect-error 'not-a-key' is not a TemperamentKey
const badTemperament: TemperamentKey = 'not-a-key';
// @ts-expect-error 'not-a-key' is not an ElementKey
const badElement: ElementKey = 'not-a-key';
// @ts-expect-error 'not-a-key' is not a Chirality
const badChirality: Chirality = 'not-a-key';
// @ts-expect-error 'not-a-key' is not a Corporeality
const badCorporeality: Corporeality = 'not-a-key';
// @ts-expect-error 'not-a-key' is not a Finish
const badFinish: Finish = 'not-a-key';

describe('generator key types stay literal unions (issue #181)', () => {
	test('valid members are assignable; nothing to assert at runtime', () => {
		// The compile-time checks above are the actual test; this just gives vitest a
		// passing assertion so the file counts as a real (not empty) test.
		expect([
			attribute,
			capability,
			gradedSense,
			temperament,
			element,
			chirality,
			corporeality,
			finish,
			badAttribute,
			badCapability,
			badGradedSense,
			badTemperament,
			badElement,
			badChirality,
			badCorporeality,
			badFinish,
		]).toHaveLength(16);
	});
});
