module.exports = {
    STAT_POINT_MAX: 999,
    STAT_POINT_MIN: 1,
    STAT_COUNT_PER_CHARACTER: 8,
    MAX_ELEMENT_COUNT_PER_CHARACTER: 3,
    //
    CHAOS: 0,
    RANDOM_WEIGHT: 0.5,
    //
    STAT_THRESHOLD_VARIABILITY: 0.25,
    LOW_THRESHOLD: 0.25,
    MEDIUM_THRESHOLD: 0.5,
    HIGH_THRESHOLD: 0.75
    //
    // STAT_THRESHOLD_VARIABILITY: 0.35,
    // LOW_THRESHOLD: 0.35,
    // MEDIUM_THRESHOLD: 0.5,
    // HIGH_THRESHOLD: 0.65
}