module.exports = {
    STANDARD_ATTACK_POINTS: "standardAttackPoints",
    SPECIAL_ATTACK_POINTS: "specialAttackPoints",
    STANDARD_DEFENSE_POINTS: "standardDefensePoints",
    SPECIAL_DEFENSE_POINTS: "specialDefensePoints",
    SPEED_POINTS: "speedPoints",
    EVASION_POINTS: "evasionPoints",
    HEALTH_POINTS: "healthPoints",
    STAMINA_POINTS: "staminaPoints",
    RECOVERY_POINTS: "recoveryPoints",
    STANDARD_ATTACK_RATING: "standardAttackRating",
    SPECIAL_ATTACK_RATING: "specialAttackRating",
    STANDARD_DEFENSE_RATING: "standardDefenseRating",
    SPECIAL_DEFENSE_RATING: "specialDefenseRating",
    SPEED_RATING: "speedRating",
    EVASION_RATING: "evasionRating",
    HEALTH_RATING: "healthRating",
    STAMINA_RATING: "staminaRating",
    RECOVERY_RATING: "recoveryRating"
}