// Builds docs/CANON_COMPENDIUM.md: the complete Xalians canon assembled into one
// readable document, grouped so that everything about a topic sits together
// (planet chapters include that planet's species descriptions and related glossary
// terms, since lore often lives only in a creature's entry).
//
// Source of truth is the JSON under lambda/src/json/ plus docs/encyclopedia/ (precedence: docs/encyclopedia/ENCYCLOPEDIA-INTERNAL.md).
// Run node scripts/bundleLore.js first so lambda/src/json/encyclopedia.json is current.
// Regenerate after any lore change:  node scripts/buildCanonCompendium.js
const fs = require('fs');
const path = require('path');

const J = (f) => JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'lambda', 'src', 'json', f), 'utf8'));
const planets = J('planetRecords.json');
const species = J('species.json');
const glossary = J('encyclopedia.json').entries.map(e => ({ word: e.title, definition: e.definition, category: e.category }));

const RATING_LABEL = {
  'optimal': 'OPTIMAL', 'viable': 'VIABLE', 'inefficient': 'INEFFICIENT',
  'unsupported': 'UNSUPPORTED', 'not-applicable': 'NOT APPLICABLE'
};

function reportBlock(r) {
  const lines = [];
  lines.push(`> **Standardized Environmental Report.** Unit: ${r.unit}${r.unitNote ? ` (${r.unitNote})` : ''}. Protocol: ${r.protocol}. Cycle: ${r.cycle}. Receipt unconfirmed.`);
  lines.push('>');
  lines.push(`> **Terrain:** ${r.terrain.features.join('; ')}. ${r.terrain.notes || ''}`.trim());
  const mob = ['flight', 'swim', 'burrow', 'climb', 'sprint']
    .map(a => { const m = r.mobility[a]; return `${a} ${RATING_LABEL[m.rating]}${m.note ? ` (${m.note})` : ''}`; })
    .join('; ');
  lines.push(`> **Mobility:** ${mob}.`);
  lines.push(`> **Extant fauna:** ${r.fauna.observations.join('. ')}.`);
  lines.push(`> **Hazards:** ${r.hazards.join('; ')}.`);
  lines.push(`> **Output priorities:** ${r.outputPriorities.join('; ')}.${r.outputNotes ? ' ' + r.outputNotes : ''}`);
  return lines.join('\n');
}

function glossaryTermsFor(name) {
  const needle = name.toLowerCase();
  return glossary.filter(g =>
    g.word.toLowerCase().includes(needle) || (g.definition || '').toLowerCase().includes(needle)
  );
}

let out = [];
out.push('# Xalians Canon Compendium');
out.push('');
out.push('The complete canonical lore in one document, assembled from the source-of-truth JSON (`lambda/src/json/`). Each planet chapter gathers everything canon says about that world: physical data, its Generator\'s environmental report, its full history, every species native to it, and encyclopedia entries that reference it. Do not edit this file directly; edit the JSON and regenerate with `node scripts/buildCanonCompendium.js`. Precedence rules: `docs/encyclopedia/ENCYCLOPEDIA-INTERNAL.md`; the undated timeline: `docs/design/xalian-chronicle.md`.');
out.push('');
out.push('## Contents');
out.push('');
planets.forEach(p => out.push(`- [${p.name} (${p.report && p.element ? cap(p.element) : ''})](#${p.name.toLowerCase()})`));
out.push('- [Full Encyclopedia](#full-encyclopedia)');
out.push('- [Species Index](#species-index)');
out.push('');

function cap(s) { return s.charAt(0).toUpperCase() + s.slice(1); }

for (const p of planets) {
  out.push('---');
  out.push('');
  out.push(`# ${p.name}`);
  out.push('');
  const ph = p.physical;
  out.push(`**Element:** ${cap(p.element)} · **Terrain:** ${ph.terrainLabel} · **Size:** ${ph.sizeVsEarth}x Earth · **Radius:** ${ph.radiusKm.toLocaleString()} km · **Gravity:** ${ph.gravityVsEarth}x Earth · **Temperature:** ${ph.temperatureC.low} to ${ph.temperatureC.high} °C`);
  out.push('');
  out.push(reportBlock(p.report));
  out.push('');
  out.push(`## History of ${p.name}`);
  out.push('');
  for (const para of p.history) out.push(para.trim(), '');

  const natives = species.filter(s => (s.planet || '').toLowerCase() === p.name.toLowerCase());
  if (natives.length) {
    out.push(`## Species of ${p.name}`);
    out.push('');
    for (const s of natives) {
      out.push(`### ${s.name} (${s.type}, id ${s.id})`);
      out.push('');
      out.push(`Height: ${s.height} · Weight: ${s.weight}`);
      out.push('');
      out.push(s.description.trim());
      out.push('');
    }
  }

  const terms = glossaryTermsFor(p.name);
  if (terms.length) {
    out.push(`## Glossary terms referencing ${p.name}`);
    out.push('');
    for (const t of terms) out.push(`- **${t.word}** — ${t.definition}`);
    out.push('');
  }
}

out.push('---');
out.push('');
out.push('# Full Encyclopedia');
out.push('');
[...glossary].sort((a, b) => a.word.localeCompare(b.word)).forEach(t => out.push(`- **${t.word}** — ${t.definition}`));
out.push('');
out.push('---');
out.push('');
out.push('# Species Index');
out.push('');
out.push('| Species | Element | Home planet | Id |');
out.push('|---|---|---|---|');
[...species].sort((a, b) => a.name.localeCompare(b.name)).forEach(s => out.push(`| ${s.name} | ${s.type} | ${s.planet} | ${s.id} |`));
out.push('');

const dest = path.join(__dirname, '..', 'docs', 'CANON_COMPENDIUM.md');
fs.writeFileSync(dest, out.join('\n'));
console.log('Wrote', dest, `(${planets.length} planets, ${species.length} species, ${glossary.length} glossary terms)`);
