#!/usr/bin/env node
/*
 * Deterministic roster inventory for creature expansion planning.
 *
 * Run:   node scripts/creatureCoverage.js
 * Check: node scripts/creatureCoverage.js --check
 *
 * This reports coverage, not power. Equal counts are not assumed to be balanced;
 * gameplay strength must be tested in a consumer or simulation.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const JSON_DIR = path.join(ROOT, 'packages', 'content', 'json');
const REPORT_PATH = path.join(ROOT, 'docs', 'design', 'CREATURE-EXPANSION-COVERAGE.md');

function read(name) {
  return JSON.parse(fs.readFileSync(path.join(JSON_DIR, name), 'utf8'));
}

function midpoint([low, high]) {
  return (low + high) / 2;
}

function mean(values) {
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

function counts(universe, values) {
  const found = new Map(universe.map((key) => [key, 0]));
  values.forEach((key) => found.set(key, (found.get(key) || 0) + 1));
  return universe.map((key) => ({ key, count: found.get(key) || 0 }));
}

function table(lines, headers, rows) {
  lines.push(`| ${headers.join(' | ')} |`);
  lines.push(`| ${headers.map(() => '---').join(' | ')} |`);
  rows.forEach((row) => lines.push(`| ${row.join(' | ')} |`));
  lines.push('');
}

function render() {
  const bundle = read('speciesRecords.json');
  const registries = read('registries.json');
  const planets = read('planetRecords.json');
  const records = bundle.records;
  const missingNameOrigins = records.filter((record) => typeof record.nameOrigin !== 'string' || !record.nameOrigin.trim());
  if (missingNameOrigins.length) {
    throw new Error(`Ratified species missing nameOrigin: ${missingNameOrigins.map((record) => record.key).join(', ')}`);
  }
  const planetByKey = new Map(planets.map((planet) => [planet.key, planet]));
  const lines = [];

  lines.push('# Creature Expansion Coverage');
  lines.push('');
  lines.push('Generated by `node scripts/creatureCoverage.js` from the ratified species bundle and registries. This is a coverage inventory, not a power ranking: scarcity identifies design space, while balance claims require generation and game-consumer tests.');
  lines.push('');
  lines.push(`Snapshot: ${records.length} ratified species; species bundle ${bundle.version}; registry ${registries.version}.`);
  lines.push('');

  lines.push('## Current creature index');
  lines.push('');
  table(lines,
    ['Species', 'Element / world', 'Body', '50+ capability ceiling', 'Special senses', 'Required traits', 'Lead archetype', 'Signature'],
    records.map((record) => {
      const p = record.physiology;
      const strongCaps = Object.entries(p.capabilities).filter(([, band]) => band[1] >= 50).map(([key]) => key);
      const requiredTraits = Object.entries(record.traits.pool).filter(([, percent]) => percent === 100).map(([key]) => key);
      const lead = Object.entries(record.archetypeWeights).sort((a, b) => b[1] - a[1])[0];
      const special = p.senses.special || [];
      const signature = record.signatureAbility;
      return [
        `${record.name} (${record.key})`,
        `${record.element} / ${planetByKey.get(record.homePlanet)?.name || record.homePlanet}`,
        `${p.bodyPlan}; ${p.composition.primary}${p.composition.secondary ? `+${p.composition.secondary}` : ''}; ${p.covering}`,
        strongCaps.join(', ') || 'none',
        special.join(', ') || 'none',
        requiredTraits.join(', ') || 'none',
        `${lead[0]} ${lead[1]}%`,
        `${signature.instrument} / ${signature.action} / ${signature.medium}`,
      ];
    }),
  );

  lines.push('## Element and world representation');
  lines.push('');
  const elementRows = registries.elements.map(({ key }) => {
    const members = records.filter((record) => record.element === key);
    const world = planets.find((planet) => planet.element === key);
    return [key, world ? world.name : 'none', String(members.length), members.map((record) => record.name).join(', ') || 'none'];
  });
  table(lines, ['Element', 'Home world', 'Species', 'Roster'], elementRows);

  lines.push('## Physiology vocabulary coverage');
  lines.push('');
  const physiologyDimensions = [
    ['Corporeality', registries.physiology.corporeality.map((x) => x.key), records.map((r) => r.physiology.corporeality)],
    ['Composition (primary or secondary)', registries.physiology.composition.map((x) => x.key), records.flatMap((r) => [r.physiology.composition.primary, r.physiology.composition.secondary].filter(Boolean))],
    ['Body plan', registries.physiology.bodyPlan.map((x) => x.key), records.map((r) => r.physiology.bodyPlan)],
    ['Covering', registries.physiology.covering.map((x) => x.key), records.map((r) => r.physiology.covering)],
    ['Diet', registries.physiology.diet.map((x) => x.key), records.map((r) => r.physiology.diet)],
    ['Communication', registries.physiology.communication.map((x) => x.key), records.flatMap((r) => r.physiology.communication)],
    ['Breathes', registries.physiology.media.map((x) => x.key), records.flatMap((r) => r.physiology.breathes)],
    ['Ambient media', registries.physiology.media.map((x) => x.key), records.flatMap((r) => r.physiology.environmentalTolerance.ambientMedia)],
    ['Lifespan', registries.physiology.lifespan.map((x) => x.key), records.map((r) => r.physiology.lifespan)],
    ['Special senses', registries.senses.slice(3).map((x) => x.key), records.flatMap((r) => r.physiology.senses.special || [])],
    ['Anatomy', registries.anatomy.map((x) => x.key), records.flatMap((r) => r.physiology.anatomy)],
  ];
  physiologyDimensions.forEach(([label, universe, values]) => {
    lines.push(`### ${label}`);
    lines.push('');
    table(lines, ['Key', 'Species using it'], counts(universe, values).map((row) => [row.key, String(row.count)]));
  });

  lines.push('## Archetype exposure');
  lines.push('');
  lines.push('Expected share assumes species are selected uniformly, then applies each species\' authored archetype percentages. It describes roster exposure, not win rate.');
  lines.push('');
  const archetypeRows = registries.archetypes.map(({ key }) => {
    const carrying = records.filter((record) => record.archetypeWeights[key] !== undefined);
    const share = records.reduce((sum, record) => sum + (record.archetypeWeights[key] || 0), 0) / records.length;
    return [key, String(carrying.length), `${share.toFixed(1)}%`];
  });
  table(lines, ['Archetype', 'Species carrying it', 'Expected equal-roster share'], archetypeRows);

  lines.push('## Trait exposure');
  lines.push('');
  lines.push('Authored landed share is the equal-roster mean of the listed percentages before trait tilts and exclusion handling. It is useful for targeting, but simulation is authoritative for generated populations.');
  lines.push('');
  const traitRows = registries.traits.map(({ key }) => {
    const pools = records.filter((record) => record.traits.pool[key] !== undefined);
    const required = records.filter((record) => record.traits.pool[key] === 100);
    const share = records.reduce((sum, record) => sum + (record.traits.pool[key] || 0), 0) / records.length;
    return [key, String(pools.length), String(required.length), `${share.toFixed(1)}%`];
  });
  table(lines, ['Trait', 'Species pools', 'Required by species', 'Authored landed share'], traitRows);

  lines.push('## Capability and attribute centers');
  lines.push('');
  const capabilityRows = registries.capabilities.map(({ key }) => {
    const bands = records.map((record) => record.physiology.capabilities[key]);
    return [key, String(bands.filter((band) => band[1] > 0).length), mean(bands.map(midpoint)).toFixed(1), Math.min(...bands.map(midpoint)).toFixed(1), Math.max(...bands.map(midpoint)).toFixed(1)];
  });
  table(lines, ['Capability', 'Non-zero ceiling', 'Mean midpoint', 'Lowest midpoint', 'Highest midpoint'], capabilityRows);
  const attributeRows = registries.attributes.map(({ key }) => {
    const mids = records.map((record) => midpoint(record.attributes[key]));
    return [key, mean(mids).toFixed(1), Math.min(...mids).toFixed(1), Math.max(...mids).toFixed(1)];
  });
  table(lines, ['Attribute', 'Mean species midpoint', 'Lowest species midpoint', 'Highest species midpoint'], attributeRows);

  lines.push('## Ability identity coverage');
  lines.push('');
  const signatureActions = counts(registries.actions.map((x) => x.key), records.map((r) => r.signatureAbility.action));
  table(lines, ['Signature action', 'Species'], signatureActions.map((row) => [row.key, String(row.count)]));
  const instrumentUniverse = [...registries.anatomy, ...registries.channels].map((x) => x.key);
  const instrumentRows = counts(instrumentUniverse, records.flatMap((record) => record.instruments));
  table(lines, ['Available instrument', 'Species'], instrumentRows.map((row) => [row.key, String(row.count)]));
  const conduits = records.flatMap((record) => Object.entries(record.conduits || {}));
  table(lines, ['Conduit medium', 'Declarations'], counts(registries.elements.map((x) => x.key), conduits.map(([, medium]) => medium)).map((row) => [row.key, String(row.count)]));

  lines.push('## Structural targeting queue');
  lines.push('');
  lines.push('These are prompts for the next design brief, not instructions to force a creature into every empty cell. A target should close two to four coherent gaps without contradicting its world, ecology, silhouette, or central ability.');
  lines.push('');
  const zero = [];
  const singleton = [];
  const addGaps = (label, rows) => rows.forEach((row) => {
    if (row.count === 0) zero.push(`${label}: ${row.key}`);
    else if (row.count === 1) singleton.push(`${label}: ${row.key}`);
  });
  // Breathing vacuum is physically incoherent (non-breathers use []), and anatomy is
  // demand-led rather than a quota. Both remain inventoried above but are not deficits.
  physiologyDimensions
    .filter(([label]) => !['Breathes', 'Anatomy'].includes(label))
    .forEach(([label, universe, values]) => addGaps(label.toLowerCase(), counts(universe, values)));
  addGaps('archetype', registries.archetypes.map(({ key }) => ({ key, count: records.filter((r) => r.archetypeWeights[key] !== undefined).length })));
  addGaps('trait pool', registries.traits.map(({ key }) => ({ key, count: records.filter((r) => r.traits.pool[key] !== undefined).length })));
  const thinElements = elementRows.filter((row) => Number(row[2]) < 2).map((row) => `${row[0]} (${row[2]})`);
  const unusedSignatureActions = signatureActions.filter((row) => row.count === 0).map((row) => row.key);
  const unusedInstruments = instrumentRows.filter((row) => row.count === 0).map((row) => row.key);
  lines.push(`1. **Roster shortages:** elements/worlds below two species: ${thinElements.length ? thinElements.join(', ') : 'none'}.`);
  lines.push(`2. **Unused reusable species vocabulary:** ${zero.length ? zero.join('; ') : 'none'}. These are prompts, not quotas.`);
  lines.push(`3. **Singleton reusable species vocabulary:** ${singleton.length ? singleton.join('; ') : 'none'}. Confirm whether rarity is intentional before targeting it.`);
  lines.push(`4. **Unused signature actions:** ${unusedSignatureActions.length ? unusedSignatureActions.join(', ') : 'none'}. These are identity opportunities, not required slots.`);
  lines.push(`5. **Available but unused instruments/channels:** ${unusedInstruments.length ? unusedInstruments.join(', ') : 'none'}. Select only when the body or ability demands one.`);
  lines.push('6. **Intentional non-target:** `vacuum` is valid ambient tolerance but not a breathing target; a creature that does not breathe uses an empty list.');
  lines.push('7. **Distribution checks:** review low archetype exposure, trait landed share, capability centers, and attribute centers through generated batches before calling any of them balance problems.');
  lines.push('8. **Collision checks:** every proposed signature must add a distinct instrument/action/medium identity and retain adequate catalog-name reachability.');
  lines.push('');
  return `${lines.join('\n')}\n`;
}

function main() {
  const report = render();
  if (process.argv.includes('--check')) {
    const existing = fs.existsSync(REPORT_PATH) ? fs.readFileSync(REPORT_PATH, 'utf8').replace(/\r\n/g, '\n') : '';
    if (existing !== report) {
      console.error('Creature expansion coverage is stale. Run node scripts/creatureCoverage.js.');
      process.exit(1);
    }
    console.log('Creature expansion coverage is up to date.');
    return;
  }
  fs.writeFileSync(REPORT_PATH, report, 'utf8');
  console.log(`Wrote ${REPORT_PATH}`);
}

module.exports = { render };

if (require.main === module) main();
