// Generate loop_workflow.js from loop_workflow.src.js plus loop_core.js.
//   node build_workflow.mjs           write loop_workflow.js
//   node build_workflow.mjs --check   exit 1 when loop_workflow.js is stale
//
// Workflow scripts cannot import files, so the core is inlined at the //@core marker with
// its `export` keywords stripped. The script must still begin with `export const meta`
// (a pure literal), so the source header sits right after it.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const MARK = '//@core'

export function build(srcText, coreText) {
  const src = srcText.replace(/\r\n/g, '\n'), core = coreText.replace(/\r\n/g, '\n')
  if (src.split('\n').filter(l => l.trim() === MARK).length !== 1) throw new Error(`loop_workflow.src.js needs exactly one ${MARK} line`)
  const inlined = core.replace(/^export\s+(?=(?:async\s+)?(?:function|const|let)\b)/gm, '')
  if (/^\s*(export|import)\s/m.test(inlined)) throw new Error('loop_core.js has an export or import the build cannot strip')
  const header = [
    '// GENERATED by art/species-construction/loop/build_workflow.mjs from loop_workflow.src.js and loop_core.js.',
    '// Edit those, then run `node build_workflow.mjs`; `node build_workflow.mjs --check` fails when this file is stale.',
  ].join('\n')
  const lines = src.split('\n')
  const metaEnd = lines.findIndex((l, i) => i > 0 && l === '}')
  if (!lines[0].startsWith('export const meta') || metaEnd < 0) throw new Error('loop_workflow.src.js must start with export const meta = {...}')
  return [...lines.slice(0, metaEnd + 1), header, ...lines.slice(metaEnd + 1)]
    .map(l => l.trim() === MARK ? `// ---- begin loop_core.js ----\n${inlined.trimEnd()}\n// ---- end loop_core.js ----` : l)
    .join('\n')
}

export function generate() {
  return build(readFileSync(join(here, 'loop_workflow.src.js'), 'utf8'), readFileSync(join(here, 'loop_core.js'), 'utf8'))
}

if (import.meta.main) {
  const target = join(here, 'loop_workflow.js')
  const text = generate()
  if (process.argv.includes('--check')) {
    let cur = ''
    try { cur = readFileSync(target, 'utf8').replace(/\r\n/g, '\n') } catch {}
    if (cur !== text) { console.error('loop_workflow.js is stale: run node art/species-construction/loop/build_workflow.mjs'); process.exit(1) }
    console.log('loop_workflow.js is current')
  } else {
    writeFileSync(target, text)
    console.log(`wrote ${target} (${text.length} bytes)`)
  }
}
